### ISSUE TITLE
Switching tabs programmatically

### ISSUE THREAD

**Issue by ThatBrianDude** [react-materialize/react-materialize#502] opened 2018-03-14 19:39 UTC
### Description

I am not able to switch tabs programmatically using the jquery $("...").tabs("select_tab", "tab_id")
method. My tabs id's are visible on the bottom left of the browser when hovering over them so I was able to confirm that they were right. 

I also tried giving a tab an explicit id prop but that doesnt work either.

Is this not implemented?

**Comment by alextrastero** [comment] 2018-03-15 11:46
Hey @ThatBrianDude, can't you pass `active` prop to child `Tab` of `Tabs`?
https://github.com/react-materialize/react-materialize/blob/master/src/Tab.js#L25

**Comment by ThatBrianDude** [comment] 2018-03-15 11:53
That only marks the tab as active but will not trigger the indicator animation. 
You end up with one tab "active" via text color and another via indicator.

**Comment by alextrastero** [comment] 2018-03-15 11:55
I see, can you explain to me a bit more your use case?

**Comment by ThatBrianDude** [comment] 2018-03-15 11:59
I am combining tabs with react-router. Each tab represents a route on my page. I have another button elsewhere on the page that also leads to one of the routes.

When I click the button I want the tabs to animate as if I clicked the tab itself instead of the button. 

Right now the route changes and the text of the target tab too but not the indicator. The indicator stays at the previous tab.

**Comment by alextrastero** [comment] 2018-03-15 12:05
Ok, so ideally you would listen to new route and then call the jQuery method, check the ID that get's assigned to each tab you want to 'select' and try calling the method. `$('ul.tabs').tabs('select_tab', 'tab_id');`

**Comment by alextrastero** [comment] 2018-03-15 12:05
If it doesn't work, what error are you getting?

**Comment by ThatBrianDude** [comment] 2018-03-19 11:09
I am not receiving any error sadly. I am however observing some very weird behaviour:

Every time I click on a tab their id's increment by 10. So they begin with tab_01 etc. then once I navigate to any tab, each of them receives a new id incremented by 10. tab_01 becomes tab_10. Maybe this is the reason .tabs("select_tab", "tab_01") never works because the transition itself already changes the id before the select_tab is actually executed?

**Comment by alextrastero** [comment] 2018-03-23 13:07
Hey @ThatBrianDude, I need a code sample to test please :)

**Comment by ThatBrianDude** [comment] 2018-03-26 10:09
Sorry I couldnt find the time to gather up a project to reproduce but you havent told me yet if the id incrementing is wanted or not. It would seem to me that thats unwanted behaviour?

Anyhow, for now I am working around this by simulating a keypress on the desired tab like so:

    <Tabs ref={ref => this.tabsRef = ref} .....


     <MyButton onClick={() => this.tabsRef._tabsEl.childNodes[2].childNodes[0].click()} />


   2 being the index of the desired tab. (starts at 1 not 0 due to the indicator element)

**Comment by ThatBrianDude** [comment] 2018-03-26 15:18
```
<Route render={(context) => (
              <Tabs ref={ref => this.tabsRef = ref} id="navigation-tabs" className="black" onChange={(tabIndex) => context.history.push(getTabPathFromIndex(tabIndex.toString().slice(-1)))}>
                <Tab id="games" title="Games" active={context.location.pathname == "/games"}></Tab>
                <Tab id="account" title="Account" active={context.location.pathname == "/account"}></Tab>
                <Tab id="donators" title="Donators" active={context.location.pathname == "/donators"}></Tab>
                <Tab id="about" title="About" active={context.location.pathname == "/about"}></Tab>

              </Tabs>)} />
```

Thats the relevant part

**Comment by alextrastero** [comment] 2018-03-26 16:34
Hey @ThatBrianDude, just checked and the id is incrementing on each render, so if you re-render the component that will change.

One solution would be to only create this ID in a constructor, but I don't understand why `active` prop is not working

**Comment by alextrastero** [comment] 2018-03-26 16:48
So after checking it's true, this needs some thought around it.

We could check for children prop `active`. Then on component update check if a new child has `active` and trigger a change tab.
 
`$('ul.tabs').tabs('select_tab', 'tab_id');`

Or should we trigger this every time something updates?
Anyhow it's a bug :)

**Comment by ThatBrianDude** [comment] 2018-03-26 16:58
I would go with triggering it each update. Shouldnt be too bad as triggering is idempotent

**Comment by alextrastero** [comment] 2018-04-05 20:58
@onluiz would you want to have a look at this one? It seems tricky :)

**Comment by onluiz** [comment] 2018-04-06 02:46
@alextrastero, for sure =)

I was capable to reproduce the problem with react-router, now I will try some of the above suggestions. =)

**Comment by alextrastero** [comment] 2018-04-06 08:44
I think if you add a method that updates state it should already break, since the `Tabs` are only initialised once, you need to add some logic on componentDidUpdate or some other lifecycle method

**Comment by onluiz** [comment] 2018-04-06 20:36
Hi @alextrastero .

Can I ask for some help? I'm having a really hard time trying to reproduce this behavior in the examples.

```
export default
<Tabs className='tab-demo z-depth-1'>
    <Tab title="Test 1">Test 1</Tab>
    <Tab title="Test 2" active>Test 2</Tab>
    <Tab title="Test 3">Test 3</Tab>
    <Tab title="Test 4">Test 4</Tab>
</Tabs>;
```

I'm modifying the code above but it seams like it doesn't work as a normal react component (I'm not being to pass prop to it from docs/TabsPage to examples/Tab). Any tip of how is the best practice to test react-materialiaze components (beside unit testing)?

**Comment by alextrastero** [comment] 2019-03-24 16:19
Please try `react-materialize3.x` and reopen if this is still happening, thanks!

**Closed by alextrastero** 2019-03-24 16:19 UTC
Labels: bug, help wanted
