### ISSUE TITLE
Something goes wrong in v1.0.9

### ISSUE THREAD

**Issue by lyczkop** [react-materialize/react-materialize#383] opened 2017-09-26 19:34 UTC
Hi, untill today I've used v1.0.6. From materialize i used only "{Table, ProgressBar, Input, Icon, Pagination, Modal, Button}"
When i upgrade to latest v.1.014 something goes wrong, my Tabs go broken and some logic to... axios from component under Tabs stop work correctly. I findout that WRONG came with v.1.0.9.
I dont know what, but something make realy mess ;/

If you have some tips, pls let me know.

**Comment by alextrastero** [comment] 2017-09-29 08:17
Hey @lyczkop, please elaborate a little more what the problem is. I've just tested the `Tabs` and they seem to work fine. Are you getting any errors in the console? Do other materialize js components work like `Carousel`?

**Comment by alextrastero** [comment] 2017-09-30 09:44
Closing, let me know if this continues to be a problem

**Closed by alextrastero** 2017-09-30 09:44 UTC
