### ISSUE TITLE
Module not found: Can't resolve '../src/TextInput'

### ISSUE THREAD

**Issue by Byte-666** [react-materialize/react-materialize#838] opened 2019-04-19 18:11 UTC
### Description

I'm having a problem when compiling using create-react-app --typescript.

### Steps to Reproduce

Importing the component and compiling:
```import { Navbar, NavItem, Divider, Dropdown } from "react-materialize" ```

The culprit changeset.
https://github.com/react-materialize/react-materialize/commit/36dc32f4591d485bdba9544547e06529dbf96399

**Expected behavior:** 
No compile error

**Actual behavior:** 
```Module not found: Can't resolve '../src/TextInput' in 'C:\test\node_modules\react-materialize\lib'```

### Versions

```
  "dependencies": {
    "@types/jest": "24.0.11",
    "@types/materialize-css": "^1.0.6",
    "@types/node": "11.13.5",
    "@types/react": "16.8.13",
    "@types/react-dom": "16.8.4",
    "materialize-css": "^1.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-materialize": "3.1.0",
    "react-scripts": "2.1.8",
    "typescript": "3.4.4"
  },
```

**Comment by paolospag** [comment] 2019-04-19 18:45
I have the same problem.
No typescript

**Comment by CloudPower97** [comment] 2019-04-19 19:19
@Byte-666 @paolospag this is fixed with #832 .
Duplicate of #837

**Comment by alextrastero** [comment] 2019-04-19 20:26
Thanks for reporting this @Byte-666 @paolospag and sorry for the trouble.
@CloudPower97 thanks for the proposal, we sure need to give this a thought, maybe a small integration test with puppeteer or similar...

**Closed** 2019-04-19 20:28 UTC

**Comment by CloudPower97** [comment] 2019-04-19 20:56
@alextrastero I've found a solution, have a look at #832
