### ISSUE TITLE
Button -> tooltip does nothing

### ISSUE THREAD

**Issue by nazarposhta** [react-materialize/react-materialize#69] opened 2016-05-25 15:04 UTC
```
<Button floating fab='vertical' icon='more_horiz' large style={{bottom: '45px', right: '24px'}}>
    <Button tooltip='Hello world!' floating icon='format_quote' className='yellow darken-1'>
        <a href=""><i className="material-icons">play_arrow</i></a>
    </Button>
</Button>
```

But I do not see some tooltip

**Comment by isaiah** [comment] 2016-06-10 10:08
Sorry, the documentation is wrong, I think this is not yet implemented. @alextrastero

**Comment by alextrastero** [comment] 2016-06-10 10:08
I will have a look at this asap

**Comment by alextrastero** [comment] 2016-09-04 17:10
Closing, cant reproduce with latest version

**Comment by johhansantana** [comment] 2017-02-04 01:31
I got this error as well

code:

```html
<a href="#">
  <Button tooltip="hello" floating large waves='light' className="bottomRightFloat">
    <i className="material-icons">add</i>
  </Button>
</a>
```

<img width="592" alt="screen shot 2017-02-03 at 9 30 05 pm" src="https://cloud.githubusercontent.com/assets/9933887/22614416/047eb5f6-ea58-11e6-96c8-932335effd80.png">

**Comment by anshulk** [comment] 2018-04-20 06:31
Tooltip still seems to do nothing for a button.

**Comment by alextrastero** [comment] 2018-04-23 11:14
True! this is not implemented.
Ideally in Button.js if tooltip prop is present we would initialise the materializejs method http://materializecss.com/tooltips.html

Anyone would like to give this a shot?

**Closed** 2018-05-11 07:46 UTC
Labels: help wanted

**Comment by wowkalucky** [comment] 2018-07-21 10:41
I'll put it here on the Error-Search-Path - it can save time for somebody.

Today I encountered strange tooltip-related error: `TypeError: $(...).tooltip is not a function`.
Then I figured out that Chrome Dev Tools automatically blocked requests for `materialize.min.js`.
If so, you may want to check `Request blocking` tab in Console section...
