### ISSUE TITLE
material_select is not a function

### ISSUE THREAD

**Issue by fengxia41103** [react-materialize/react-materialize#381] opened 2017-09-22 12:40 UTC
Followed doc for installation:

  <body>
    <div id="app" />
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

    <script type="text/javascript"
            src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="bundle.js"
            type="text/javascript"></script>
  </body>

Trying to use `Select` in jsx, error `material_select` is not a function:
```
import React from 'react';
import { Button, Card, Row, Col, Input } from 'react-materialize';
....

return (
<Row>
	<Input s={12} type='select' label="Materialize Select" defaultValue='2'>
		<option value='1'>Option 1</option>
		<option value='2'>Option 2</option>
		<option value='3'>Option 3</option>
	</Input>
</Row>
)
```

Help.

**Comment by alextrastero** [comment] 2017-09-22 14:01
Hey @fengxia41103, a couple questions to help you out,
- Does `Modal` component work?
- Are you using `create-react-app`?

**Comment by fengxia41103** [comment] 2017-09-22 14:25
Modal works.

No I'm not using `create-react-app`. This is an existing app we are adapting to materialize-css.

**Comment by fengxia41103** [comment] 2017-09-22 14:28
Don't know if this is related.

Modal demo on `https://react-materialize.github.io/#/` doesn't popup for me either.

I'm using Ubuntu 16.04 Chrome.

**Comment by fengxia41103** [comment] 2017-09-22 14:29
Console error:

Uncaught TypeError: Cannot read property 'getDOMNode' of undefined
    at OverlayTrigger.getContainerDOMNode (Overlay.js:95)
    at OverlayTrigger._mountOverlayTarget (Overlay.js:65)
    at OverlayTrigger._renderOverlay (Overlay.js:71)
    at OverlayTrigger.componentDidMount (Overlay.js:59)
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at batchedMountComponentIntoNode (ReactMount.js:126)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:140)

Tested on windows 10 chrome, also, same error.

**Comment by alextrastero** [comment] 2017-09-22 14:34
Ah yes, this is updated now, docs needed the latest version

**Comment by alextrastero** [comment] 2017-09-22 14:35
But forms work fine here: https://react-materialize.github.io/#/forms

**Comment by fengxia41103** [comment] 2017-09-22 14:42
Yes I see the forms are working well. What did I miss? any suggestion?

**Comment by alextrastero** [comment] 2017-09-22 14:48
Normally the issue is with `materialize.js` not being loaded, but if `Modal` works then it's something else. Can you paste the exact error here? also please try other materializejs components like dropdown

**Comment by alextrastero** [comment] 2017-09-22 14:49
related issue? https://github.com/Dogfalo/materialize/issues/4521#issuecomment-293172209

**Comment by fengxia41103** [comment] 2017-09-22 15:17
Got me further based on #4521 above.

Both Modal and Select now rendered, sort of. 

Modal pops up, but with a larger white box around it so sizing is incorrect. 
Select has two `down arrorws` adjacent to each other, clicking it has no effect.

This app has been using material css for a while, so I think the issue is related to how jquery & material are loaded since these components are really jQuery plugins.

**Comment by fengxia41103** [comment] 2017-09-22 17:16
Figured it out!

The app has also loaded Bootstrap (legacy). 

```
/* require("bootstrap/dist/css/bootstrap.min.css");*/
/* require("bootstrap");*/
```
Commented these lines out and it is all working :)

**Comment by fengxia41103** [comment] 2017-09-22 17:18
So to fully make this work:

1. Make sure there is no Bootstrap loaded.
2. in `main.js`, 

```
import 'materialize-css/dist/js/materialize.min.js'
import 'materialize-css/dist/css/materialize.min.css'
```
3. in `your.js`, 
```
import $ from 'jquery' //this one is not needed if your eslint is disabled
import { Button, Card, Row, Col, Input, Modal, Icon } from 'react-materialize';
```

**Comment by alextrastero** [comment] 2017-09-24 09:43
Cool! closing then :)

**Closed by alextrastero** 2017-09-24 09:43 UTC

**Comment by pkenjora** [comment] 2018-03-16 23:18
Use version: https://github.com/Dogfalo/materialize/releases/tag/v0.100.2

**Comment by alvaradovex** [comment] 2018-06-07 12:11
If you are using latest version´s Materialize, you should change in your js. 

/*older
      $('select').material_select();
      $('#select').material_select();  */
/*newer*/
      $('select').formSelect();
