### ISSUE TITLE
Card render not using keys properly

### ISSUE THREAD

**Issue by arcifius** [react-materialize/react-materialize#150] opened 2016-09-20 14:46 UTC
Well.. I've added key on Card component but nothing happens, perhaps is something internal?

Just try to render a Card with image and you'll see:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Card`. It was passed a child from <Some  Component>. See https://fb.me/react-warning-keys for more information.

**Comment by wedneyyuri** [comment] 2016-09-20 14:58
Are you passing the `key` property properly?

```

  render: function() {
    var results = this.props.results;
    return (
      <div>
        {results.map(function(result) {
          return <Card key={result.id} />;
        })}
      <div>
    );
  }

```

**Comment by arcifius** [comment] 2016-09-20 15:07
Yeah, i'm using this:

>let rendered = this.state.highlighted.map((destaque, key) => {
>            let imagePath = (DEBUG) ? "http://silvestrini.localhost" + destaque.imagem : destaque.imagem;
>
>           return(
>                <Col s={12} m={6} l={3} key={key}>
>                    <Card className='small'
>                        header={<CardTitle image={imagePath}>DESTAQUE {key+1}</CardTitle>}
>                        actions={[<a onClick={this._handleHighlightModify(key)} href='#!'>MODIFICAR</a>]}>
>                        <span className="truncate">{destaque.descricao}</span>
>                    </Card>
>                </Col>
>            );
>        });
>
>        return rendered;

Also tried to pass key (<Card key={key+2} .../> to avoid unique constraints) to card but got the same warning...

**Comment by alextrastero** [comment] 2016-09-20 15:18
Yes, i'm also getting this error, lemme check it out

**Comment by alextrastero** [comment] 2016-09-20 15:44
So the issue is that `actions` is an array so each element needs a key:
```js
actions={[<a key='pinpon' onClick={this._handleHighlightModify(key)} href='#!'>MODIFICAR</a>]}>
```

**Comment by alextrastero** [comment] 2016-09-20 15:51
closing, let me know if any further issues

**Closed by alextrastero** 2016-09-20 15:51 UTC
