### ISSUE TITLE
Navbar color gets grayed out

### ISSUE THREAD

**Issue by pleopardi** [react-materialize/react-materialize#289] opened 2017-06-27 15:48 UTC
Hi, here is the problem I'm having: on small screens, that is when the Navbar becomes a SideNav, the background color gets very dark. 
This happens when I change the default color for the Navbar, for example: `<Navbar className="light-blue darken-4">`.

Below the screen of the resulting Navbar:

![screenshot](https://user-images.githubusercontent.com/22129342/27596667-87527a52-5b60-11e7-843a-5a41a31d0691.png)

Any suggestion/workaround?

**Comment by alextrastero** [comment] 2017-06-27 15:52
This is the overlay added to the content when the `Navbar` is visible, I can't reproduce

**Comment by pleopardi** [comment] 2017-06-27 16:12
So, if I understood correctly your answer, that gray overlay is the default behavior when the Sidenav opens and I have to use custom CSS if I want to change it to a white background, right?

One more question: I saw that in the Sidenav when I hover over an item that item doesn't get highlighted. Am I missing some option or do I have to use custom CSS for this too?

**Comment by xGouley** [comment] 2017-06-28 15:16
No, I have the same problem:
when you use fixed on navbar, then the side nav is behind the gray layer.
If you remove "fixed", then it works well.

but in fact, we need to work in fixed mode as well...

**Comment by alextrastero** [comment] 2017-06-28 15:19
ah I see... ok let me have a look at it

**Comment by alextrastero** [comment] 2017-06-28 17:29
Yup, i'm afraid this is a `materialize.css` bug. https://github.com/Dogfalo/materialize/issues/3844
There are a couple workarounds mentioned in the issue. Since the issue is only for fixed navbar and on mobile view I can't change the render structure without changing the entire component.
CSS solutions include:
`#sidenav-overlay { margin-left: 300px; }`
`#sidenav-overlay { z-index: 1; }`
`#sidenav-overlay {  left: 300px; }`
`.navbar-fixed { z-index: 999; }`

Please let me know how it goes

**Comment by xGouley** [comment] 2017-06-29 06:49
.navbar-fixed z-index is OK for me.
But:
if z-index = 999, then I cannot click on the navbar to close the sidenav, i must click below.
if z-index = 998, then I can.

**Comment by pleopardi** [comment] 2017-06-29 07:27
Thank you for the answers! I'll definitely make some tests today and tomorrow and get back with the best workaround among those suggested.

**Closed** 2017-06-30 07:31 UTC

**Comment by PiyushMishra** [comment] 2017-12-27 12:19
<nav style="position:fixed;z-index:1;top:0" </nav> will solve the issue

**Comment by PiyushMishra** [comment] 2017-12-27 12:19
<nav style="position:fixed;z-index:1;top:0"

**Comment by sujanhbg** [comment] 2021-09-14 04:22
put #nav-mobile or .side name outside of #navbar-fixed
